import Head from 'next/head'
import Review from '../components/review'
import Image from 'next/image'
import styled from 'styled-components'

const SectionStyle = styled.div`
  section{
    height: 100vh;
    width: 100%;
    background-color: cyan;
    &:nth-child(2){
      background-color: purple;
    }
  }

  .sectionTitle{
    text-align: center;
    font-weight:400;
    margin-bottom:100px;

      span{
        font-weight:bold;
      }
  }

  .containerReview{
    padding:0 100px;
    display: flex;
    justify-content:space-around;
  }
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionStyle>
        <section id='section1'></section>
        <section id='section2'></section>
        <h2 className='sectionTitle'>Vos <span>avis</span> et <span>ressenties</span> comptes</h2>
        <div className='containerReview'>
        <Review srcPhoto="/logo.svg" nom="Jérémy Ferrier" statut="Grand-Père" testimony="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Ut enim ad minim veniam, quis nostrud exercitation ullamco laboris nisi ut aliquip ex ea commodo consequat. Duis aute irure dolor in reprehenderit in voluptate velit esse cillum dolore" />
        <Review srcPhoto="/logo.svg" nom="Marine Tourret" statut="Grand-Mère" testimony="Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua." />
        <Review srcPhoto="/logo.svg" nom="Jimmy Renden" statut="Grand-Père" testimony="Lorem ipsum dolor sit amet" />
        </div>
      </SectionStyle>
    </div>
  )
}
