import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'
import Hero from '../components/Hero'

const SectionStyle = styled.div`
  section{
    height: 100vh;
    width: 100%;
    background-color: cyan;
    &:nth-child(2){
      background-color: purple;
    }
  }
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
      </Head>
      <SectionStyle>
        < Hero/>
        
        <section id='section2'></section>
      </SectionStyle>
    </div>
  )
}
