import Head from 'next/head'
import Image from 'next/image'
import styled from 'styled-components'

const SectionStyle = styled.div`
  section{
    height: 100vh;
    width: 100%;
  }
`

export default function Home() {
  return (
    <div>
      <Head>
        <title>Create Next App</title>
        <meta name="description" content="Generated by create next app" />
        <link rel="icon" href="/favicon.ico" />
        <link rel="preconnect" href="https://fonts.googleapis.com"/>
        <link rel="preconnect" href="https://fonts.gstatic.com" crossorigin/>
        <link href="https://fonts.googleapis.com/css2?family=Inter:wght@100;400;500;700&display=swap" rel="stylesheet"/>
      </Head>
      <SectionStyle>
      <section id='section1'></section>
      <section id='section2'></section>
        </SectionStyle>
    </div>
  )
}
